services:
  - type: web
    name: film-reviews
    runtime: python
    repo: https://github.com/niconico252525/film-reviews
    plan: free
    region: singapore
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn app.wsgi:application --bind 0.0.0.0:$PORT --access-logfile - --error-logfile -
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: film-reviews-db
          property: connectionString
      - key: SECRET_KEY_SEED
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"

databases:
  - name: film-reviews-db
    plan: free
    region: singapore
    databaseName: film_reviews
    user: film_reviews
    ipAllowList: []
